version: 2

registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.GH_PKG_REGISTRY_TOKEN}}

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: wednesday
      time: "00:00"

    # Only accept updates that have been published for at least 3 days
    cooldown:
      default-days: 3

    # Create a grouped PR for minor/patch updates with majors getting dedicated PRs
    groups:
      actions:
        update-types:
          - patch
          - minor

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: wednesday
      time: "00:00"

    # Allow usage of any registry including npm-github w/ auth as above
    registries: "*"

    # Only accept updates that have been published for at least 3 days
    cooldown:
      default-days: 3

    # Ensure the new version is stored in `package.json`
    versioning-strategy: increase

    groups:
      # Create dedicated (grouped) PRs for Next.js/trpc/prisma/tailwind dependencies
      next:
        patterns:
          - "next"
          - "@next/*"
          - "@vercel/*"
      trpc:
        patterns:
          - "@trpc/*"
          - "@tanstack/react-query"
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"
          - "@auth/prisma-adapter"
      tailwind:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
          - "@headlessui/react"
      twurple:
        patterns:
          - "@twurple/*"

      # Update `dependencies` and `devDependencies` separately
      # Create grouped PRs for minor/patch updates with majors getting dedicated PRs
      # Ignore the above groups/dependencies to avoid issues when Dependabot rebases
      production:
        dependency-type: production
        update-types:
          - patch
          - minor
        exclude-patterns:
          - "next"
          - "@next/*"
          - "@vercel/*"
          - "@trpc/*"
          - "@tanstack/react-query"
          - "prisma"
          - "@prisma/*"
          - "@auth/prisma-adapter"
          - "tailwindcss"
          - "@tailwindcss/*"
          - "@headlessui/react"
          - "@twurple/*"
      development:
        dependency-type: development
        update-types:
          - patch
          - minor
        exclude-patterns:
          - "next"
          - "@next/*"
          - "@vercel/*"
          - "@trpc/*"
          - "@tanstack/react-query"
          - "prisma"
          - "@prisma/*"
          - "@auth/prisma-adapter"
          - "tailwindcss"
          - "@tailwindcss/*"
          - "@headlessui/react"
          - "@twurple/*"

    # Manually update major versions of `@types/node` with the version specified within .nvmrc
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - version-update:semver-major

    # Manually request rebases for each PR as we get to it
    # Avoids spamming Vercel with extra builds when there are lots of Dependabot PRs
    rebase-strategy: disabled

    # Allow enough PRs for all the groups plus some major version PRs
    open-pull-requests-limit: 20
