name: Update Presets

on:
  workflow_dispatch:
  schedule:
    # Run every day at midnight to sync any changes from the day
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Authenticate GitHub Package Registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Update presets data
        working-directory: ./apps/website
        run: pnpm build:presets

      - name: Check diff
        id: diff
        run: |
          # Check if there are any changes within the presets
          if ! git status --porcelain | grep 'apps/website/src/data/presets/'; then
            echo "No changes to commit."
            exit 0
          fi

          echo "diff=true" >> $GITHUB_OUTPUT

      - name: Create PR
        if: steps.diff.outputs.diff == 'true'
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ secrets.GH_PR_TOKEN }}
          title: Update presets data
          body: |
            Generated via `pnpm build:presets` in `apps/website`.

            Check this workflow's logs at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}.
          commit-message: Update presets data
          branch: automated/presets
