name: Update Chatbot
on:
  push:
    branches:
      - "main"
      - "preview"
    paths:
      - "apps/chatbot/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
      - ".github/workflows/update-chatbot.yml"

env:
  COMPOSE_PROJECT_NAME: ${{ vars.CHATBOT_COMPOSE_PROJECT_NAME }}
  CHATBOT_PATH: ${{ vars.CHATBOT_PATH }}
  REF_NAME: ${{ github.ref_name }}
  REF_SHA: ${{ github.sha }}

jobs:
  update-chatbot-production:
    name: Update Chatbot (Production)
    runs-on: ubuntu-latest
    environment: production
    if: github.repository == 'alveusgg/alveusgg' && github.ref == 'refs/heads/main'
    steps:
      - name: Update Chatbot SSH (Production)
        uses: appleboy/ssh-action@91f3272fc5907f4699dcf59761eb622a07342f5a # v1.2.3
        with:
          envs: COMPOSE_PROJECT_NAME,CHATBOT_PATH,REF_NAME,REF_SHA
          host: ${{ secrets.CHATBOT_HOST }}
          username: ${{ secrets.CHATBOT_USERNAME }}
          key: ${{ secrets.CHATBOT_KEY }}
          port: ${{ secrets.CHATBOT_PORT }}
          passphrase: ${{ secrets.CHATBOT_PASSPHRASE }}
          script: |
            set -e
            cd $CHATBOT_PATH
            git fetch origin $REF_NAME && git reset --hard origin/$REF_NAME
            cd apps/chatbot
            CHATBOT_REF_SHA=$REF_SHA docker compose up --build --detach

  update-chatbot-preview:
    name: Update Chatbot (Preview)
    runs-on: ubuntu-latest
    environment: preview
    if: github.ref == 'refs/heads/preview'
    steps:
      - name: Update Chatbot SSH (Preview)
        uses: appleboy/ssh-action@91f3272fc5907f4699dcf59761eb622a07342f5a # v1.2.3
        with:
          envs: COMPOSE_PROJECT_NAME,CHATBOT_PATH,REF_NAME,REF_SHA
          host: ${{ secrets.CHATBOT_HOST }}
          username: ${{ secrets.CHATBOT_USERNAME }}
          key: ${{ secrets.CHATBOT_KEY }}
          port: ${{ secrets.CHATBOT_PORT }}
          passphrase: ${{ secrets.CHATBOT_PASSPHRASE }}
          script: |
            set -e
            cd $CHATBOT_PATH
            git fetch origin $REF_NAME && git reset --hard origin/$REF_NAME
            cd apps/chatbot
            CHATBOT_REF_SHA=$REF_SHA docker compose up --build --detach
