name: Update Presets

on:
  workflow_dispatch:
  schedule:
    # Run every day at midnight to sync any changes from the day
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Authenticate GitHub Package Registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Update presets data
        working-directory: ./apps/website
        run: pnpm build:presets

      - name: Check diff
        id: diff
        run: |
          # Check if there are any changes within the presets
          if ! git status --porcelain | grep 'apps/website/src/data/presets/'; then
            echo "No changes to commit."
            exit 0
          fi

          echo "diff=true" >> $GITHUB_OUTPUT

      - name: Create PR
        if: steps.diff.outputs.diff == 'true'
        uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # v7.0.9
        with:
          token: ${{ secrets.GH_PR_TOKEN }}
          title: Update presets data
          body: Generated via `pnpm build:presets` in `apps/website`
          commit-message: Update presets data
          branch: automated/presets
